name: Deploy EKS

on:
  workflow_call:
    inputs:
      REGION:
          description: "Name of the region to connect to."
          required: true
          type: string
      ENV:
          description: "Name of the EKS environment where the docker image will be deployed."
          required: true
          type: string
      NAMESPACE:
          description: "Name of the EKS namespace where the docker image will be deployed."
          required: true
          type: string
      SERVICE:
          description: "Name of the service to be deployed."
          required: true
          type: string
      IMAGE_TAG:
          description: "Tag of docker image present in ECR"
          required: true
          type: string
      HELM_CHART:
          description: "Helm folder"
          required: false
          default: "kubernetes"
          type: string
jobs:
    DeployEKS:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v3
            with:
                submodules: true
                fetch-depth: 0

        -   uses: azure/setup-helm@v3
            with:
                version: 'v3.12.1'

        -   uses: azure/setup-kubectl@v3
            with:
                version: 'v1.25.13'

        -   name: Add profile credentials to ~/.aws/credentials
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
            run: |
              aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PEP }} --profile ${{ secrets.AWS_PROFILE }}
              aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }} --profile ${{ secrets.AWS_PROFILE }}

        -   name: Generate kubeconfig and setting context
            run: |
                aws eks --region ${{ inputs.REGION }} update-kubeconfig --name eks_cluster_pep --profile ${{ secrets.AWS_PROFILE }}
                kubectl config set-context --current --namespace ${{ inputs.NAMESPACE }}
                kubectl get pods
            shell: bash

        -   name: Ensure Kubernetes Namespace Exists
            env:
              NAMESPACE: ${{ inputs.NAMESPACE }}
            run: |
              if ! kubectl get namespace $NAMESPACE; then
                kubectl create namespace $NAMESPACE
              fi
            shell: bash

        - name: Checkout project's Chart.yaml
          uses: actions/checkout@v4
          with:
            repository: 'porqueeuprogramo/${{ inputs.SERVICE }}'

        -   name: Building Helm dependencies
            run: |
                helm dependency build ${{ inputs.HELM_CHART }}
            shell: bash

        -   name: Deploy Helm Chart to Kubernetes
            env:
                ENVIRONMENT: ${{ inputs.ENV }}
                AWS_REGION: ${{ inputs.REGION }}
                HELM_WORKING_DIRECTORY: ${{inputs.helm-working-directory}}
                WORKSPACE: ${{ github.workspace }}
                NAMESPACE: ${{ inputs.NAMESPACE }}
                SERVICE: ${{ inputs.SERVICE }}
            run: |
                helm upgrade --install ${{ inputs.SERVICE}} ${{ inputs.HELM_CHART }} --set app.properties.content=${{ inputs.CONTENT }} --set image.tag=${{ inputs.IMAGE_TAG }} -f ${{ inputs.HELM_CHART}}/values/values-${{ inputs.ENV }}.yaml --namespace=${{ inputs.NAMESPACE }}
            shell: bash