name: Init Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose envs to deploy to'
        required: false
        default: "dev"
    secrets:
      AWS_ACCESS_KEY_ID_PEP:
        required: true
      AWS_SECRET_ACCESS_KEY_PEP:
        required: true

jobs:
  DeployEKS:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'pep-restaurant-ms-manager' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy EKS
        uses: ./.github/actions/deployEKS.yml
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
          REGION: ${{ inputs.awsRegion }}
          ENV: ${{ inputs.stage }}
          NAMESPACE: "pep"
          SERVICE: pep-${{ matrix.service }}
          IMAGE_TAG: "latest-${{ inputs.env }}"
          HELM_CHART: "kubernetes"