name: Init Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose envs to deploy to'
        required: false
        default: "dev"
    secrets:
      AWS_ACCESS_KEY_ID_PEP:
        required: true
      AWS_SECRET_ACCESS_KEY_PEP:
        required: true

jobs:
  DeployEnvs:
    uses: ./.github/workflows/envsDeploy.yml
    with:
      env: ${{ inputs.env }}
  Runterraform:
    needs: [DeployEnvs]
    secrets: inherit
    uses: ./.github/workflows/runTerraform.yml
    with:
      env: ${{ inputs.env }}