name: Init Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose envs to deploy to'
        required: false
        default: "dev"

jobs:
  DeployEnvs:
    uses: ./.github/workflows/envsDeploy.yml
    with:
      env: ${{ inputs.env }}
  Runterraform:
    needs: [DeployEnvs]
    secrets: inherit
    uses: ./.github/workflows/runTerraform.yml
    with:
      env: ${{ inputs.env }}
  DeployEKS:
    strategy:
      matrix:
        service: [ 'pep-restaurant-ms-manager' ]
    uses: ./.github/workflows/deployEKS.yml
    with:
      REGION: eu-west-2
      ENV: ${{ inputs.env }}
      NAMESPACE: "pep"
      SERVICE: pep-${{ matrix.service }}
      IMAGE_TAG: "latest"
      HELM_CHART: "kubernetes"