name: Run Terraform

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      phase:
        required: true
        type: string

jobs:
  RunTerraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Running Terraform phase
        run: |
          echo  "Run terraform phase ${{ inputs.phase }}"

      - name: Checkout reusable Actions
        uses: actions/checkout@v2
        with:
          repository: 'porqueeuprogramo/pep-restaurant-infra'
          ref: 'feature/eks-pod-run'

      - name: Add profile credentials to ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PEP }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }} --profile ${{ secrets.AWS_PROFILE }}

      - name: Terraform Init phase ${{ inputs.phase }}
        run: terraform init
        working-directory: ./phase${{ inputs.phase }}

      - name: Terraform Plan phase ${{ inputs.phase }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PEP }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }} --profile ${{ secrets.AWS_PROFILE }}
          terraform plan
        working-directory: ./phase${{ inputs.phase }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
          aws-region: eu-west-2

      - name: Terraform Apply phase ${{ inputs.phase }}
        working-directory: ./phase${{ inputs.phase }}
        run: terraform apply -state=terraform.tfstate -auto-approve

      - name: Upload Terraform phase ${{ inputs.phase }} state file to S3
        run: aws s3 cp ./phase${{ inputs.phase }}/terraform.tfstate s3://terraform-state-pep/phase${{ inputs.phase }}/terraform.tfstate