name: Run Terraform

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  RunTerraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Running Terraform
        run: |
          echo  "Run terraform ${{ inputs.env }}"

      - name: Checkout reusable Actions
        uses: actions/checkout@v2
        with:
          repository: 'porqueeuprogramo/pep-restaurant-infra'

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PEP }} --profile ${{ secrets.AWS_PROFILE }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }} --profile ${{ secrets.AWS_PROFILE }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}
          aws-region: eu-west-2

      - name: Download Terraform state file from S3
        run: aws s3 cp s3://terraform-state-pep/terraform.tfstate terraform.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PEP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PEP }}

      - name: Terraform Apply
        run: terraform apply -state=terraform.tfstate -auto-approve
        working-directory: ./

      - name: Upload Terraform state file to S3
        run: aws s3 cp terraform.tfstate s3://terraform-state-pep/terraform.tfstate